Repository kunalkeshan/SRMIST-B.Tech-ECE-Notes-2022-24, pull requests merged in 2022-10, with the labels that each got.

#63 Updated Contribution Document
  CONTRIBUTING.md
Labels: client, hacktoberfest-accepted

#67 Issues container image restricted
  src/pages/ContributeRequests.jsx
Labels: client, hacktoberfest-accepted

#68 fix: updated background color of search items on hover
  src/components/search/CourseResult.jsx
  src/components/search/ExtraNotesResult.jsx
  src/components/search/SemResult.jsx
Labels: client, hacktoberfest-accepted

#73 Feedback Modal Added
  src/App.jsx
  src/components/layouts/CallToAction.jsx
  src/components/layouts/Footer.jsx
  src/components/reuseable/FeedbackModal.jsx
  src/config/index.js
Labels: client, hacktoberfest-accepted

#78 complete unit 2
  Semester 3/Transforms and Boundary Value Problems/Notes/UNIT-2.pdf
Labels: notes, hacktoberfest-accepted

#81 complete unit 1
  Semester 3/Transforms and Boundary Value Problems/Notes/Unit 1 PDE/Unit-1-PDE PDF Notes.pdf
Labels: notes, hacktoberfest-accepted

#82 Added Feedback from.
  README.md
  Semester 1/README.md
  Semester 2/README.md
  Semester 3/README.md
  Semester 4/README.md
  Semester 5/README.md
  Semester 6/README.md
  Semester 7/README.md
  Semester 8/README.md
Labels: documentation, hacktoberfest-accepted

#83 Added unit 3 to emtl
  Semester 3/Electromagnetics and Transmission Lines/Notes/unit-3.ppt
Labels: notes, hacktoberfest-accepted

#85 chore: removed extra spaces
  README.md
Labels: documentation, enhancement

#87 Documentation Updates
  README.md
  Semester 1/README.md
  Semester 2/README.md
  Semester 5/README.md
Labels: documentation, hacktoberfest-accepted

#91 docs: added feedback link in table of contents
  Semester 2/README.md
Labels: documentation, hacktoberfest-accepted

#92 docs: added feedback link in table of contents
  Semester 3/README.md
Labels: documentation, hacktoberfest-accepted

#93 docs: added feedback link in table of contents
  Semester 4/README.md
Labels: documentation, hacktoberfest-accepted

#88 docs: added feedback in table of contents
  README.md
Labels: documentation, hacktoberfest-accepted

#89 Documentation Updates
  README.md
Labels: documentation, hacktoberfest-accepted
